set_attribute:
  name: Set attribute
  description: Sets custom attribute for an area
  fields:
    name:
      name: name
      required: true
      example: "Location"
      selector:
        text:
    values:
      name: name
      required: true
      example: "[Indoor, Outdoor]"
      selector:
        object:

remove_attribute:
  name: Remove attribute
  description: Removes custom attribute for an area
  fields:
    name:
      name: Name
      required: true
      example: "Location"
      selector:
        text:

set_entity:
  name: Set entity
  description: Sets custom entity rule for an area
  fields:
    name:
      name: name
      required: true
      example: "Security Status"
      selector:
        text:
    domain:
      name: domain
      required: true
      example: "binary_sensor"
      selector:
        select:
          options:
            - label: Binary Sensor
              value: binary_sensor
            - label: Sensor
              value: sensor
            - label: Switch
              value: switch
            - label: Light
              value: light
    attribute:
      name: attribute
      required: true
      example: "device_class"
      selector:
        text:
    values:
      name: name
      required: true
      example: "[motion, sound]"
      selector:
        object:
    include_nested:
      name: Include Nested Areas
      required: true
      example: "True"
      selector:
        boolean:

remove_entity:
  name: Remove entity
  description: Removes custom entity rule for an area
  fields:
    name:
      name: Name
      required: true
      example: "Security Status"
      selector:
        text:
