set_area_type:
  name: Set area type
  description: Add area type
  fields:
    type:
      name: Type
      required: true
      example: "Bedroom"
      selector:
        text:

remove_area_type:
  name: Remove area type
  fields:
    type:
      name: Type
      required: true
      example: "Bedroom"
      selector:
        text:

set_entity:
  name: Set area entity
  description: Add or update area entity
  fields:
    name:
      name: Name
      required: true
      example: "Security Status"
      selector:
        text:
    domain:
      name: Domain
      required: true
      example: "binary_sensor"
      selector:
        select:
          options:
            - label: Binary Sensor
              value: binary_sensor
            - label: Camera
              value: camera
            - label: Cover
              value: cover
            - label: Light
              value: light
            - label: Sensor
              value: sensor
            - label: Switch
              value: switch
    attributes:
      name: Attributes
      required: true
      example:
        - name: device_class
          values:
            - smoke
            - gas
      selector:
        object:

remove_entity:
  name: Remove area entity
  fields:
    type:
      name: Type
      required: true
      example: "Security Status"
      selector:
        text:
