set_area_attribute:
  name: Set area attribute
  description: Set area attribute
  fields:
    name:
      name: name
      required: true
      example: "Location"
      selector:
        text:
    values:
      name: name
      required: true
      example: "[Indoor, Outdoor]"
      selector:
        object:

remove_area_attribute:
  name: Remove area type
  fields:
    name:
      name: Name
      required: true
      example: "Location"
      selector:
        text:

set_area_entity:
  name: Set area entity
  description: Set area entity
  fields:
    name:
      name: name
      required: true
      example: "Security Status"
      selector:
        text:
    domain:
      name: domain
      required: true
      example: "binary_sensor"
      selector:
        select:
          options:
            - label: Binary Sensor
              value: binary_sensor
            - label: Sensor
              value: sensor
            - label: Switch
              value: switch
            - label: Select
              value: select
            - label: Light
              value: light
    attribute:
      name: attribute
      required: true
      example: "device_class"
      selector:
        text:
    values:
      name: name
      required: true
      example: "[motion, sound]"
      selector:
        object:

remove_area_entity:
  name: Remove area entity
  fields:
    name:
      name: Name
      required: true
      example: "Security Status"
      selector:
        text:
